In [1]:
from pyvizml import CreateNBAData
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from pyvizml import GradientDescent
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
train = pd.read_csv("https://kaggle-getting-started.s3-ap-northeast-1.amazonaws.com/house-prices/train.csv")
X = train['GrLivArea'].values.reshape(-1, 1)
y = train['SalePrice'].values
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.intercept_) # w_0
print(lr.coef_) # w_1

30774.03773616199
[98.50395317]


In [3]:
X

array([[1710],
       [1262],
       [1786],
       ...,
       [2340],
       [1078],
       [1256]], dtype=int64)

In [4]:
X.max() - X.min() # 5308
X.min() # 334

334

In [5]:
mms = MinMaxScaler()
X_scaled = mms.fit_transform(X)
X_scaled

array([[0.25923135],
       [0.17483044],
       [0.27354936],
       ...,
       [0.37792012],
       [0.14016579],
       [0.17370008]])

In [6]:
mms.data_range_ # [5308]
mms.data_min_ # [334]

array([334.])

In [7]:
(X - X.min()) / (X.max() - X.min())

array([[0.25923135],
       [0.17483044],
       [0.27354936],
       ...,
       [0.37792012],
       [0.14016579],
       [0.17370008]])

In [8]:
X_train, X_valid, y_train, y_valid = train_test_split(X_scaled, y, test_size=0.33, random_state=42)
gd = GradientDescent()
gd.fit(X_train, y_train, epochs=100000, learning_rate=0.01)

epoch:      0 - loss: 38574693099.827255
epoch:  10000 - loss: 3197795772.921622
epoch:  20000 - loss: 3142864603.110587
epoch:  30000 - loss: 3141503145.540297
epoch:  40000 - loss: 3141469402.098785
epoch:  50000 - loss: 3141468565.774635
epoch:  60000 - loss: 3141468545.046515
epoch:  70000 - loss: 3141468544.532774
epoch:  80000 - loss: 3141468544.520041
epoch:  90000 - loss: 3141468544.519726


In [9]:
print(gd.intercept_) # w_0_scaled
print(gd.coef_)      # w_1_scaled

63674.359120602545
[522858.97891743]


In [10]:
gd.intercept_ - (mms.data_min_ / mms.data_range_) * gd.coef_ # w_0

array([30774.03904554])

In [11]:
gd.coef_ / mms.data_range_ # w_1

array([98.50395232])

In [12]:
ss = StandardScaler()
X_scaled = ss.fit_transform(X)
X_scaled

array([[ 0.37033344],
       [-0.48251191],
       [ 0.51501256],
       ...,
       [ 1.56964722],
       [-0.83278768],
       [-0.49393395]])

In [13]:
ss.mean_ # 1515.46369863
ss.scale_ # 525.30039356

array([525.30039356])

In [14]:
X.mean()
X.std()

525.3003935623227

In [15]:
(X - X.mean()) / X.std()

array([[ 0.37033344],
       [-0.48251191],
       [ 0.51501256],
       ...,
       [ 1.56964722],
       [-0.83278768],
       [-0.49393395]])

In [16]:
X_train, X_valid, y_train, y_valid = train_test_split(X_scaled, y, test_size=0.33, random_state=42)
gd = GradientDescent()
gd.fit(X_train, y_train, epochs=100000, learning_rate=0.01)

epoch:      0 - loss: 38574701424.678940
epoch:  10000 - loss: 3141468544.519717
epoch:  20000 - loss: 3141468544.519717
epoch:  30000 - loss: 3141468544.519717
epoch:  40000 - loss: 3141468544.519717
epoch:  50000 - loss: 3141468544.519717
epoch:  60000 - loss: 3141468544.519717
epoch:  70000 - loss: 3141468544.519717
epoch:  80000 - loss: 3141468544.519717
epoch:  90000 - loss: 3141468544.519717


In [17]:
print(gd.intercept_) # w_0_scaled

180053.20294084633


In [18]:
print(gd.coef_) # w_1_scaled

[51744.16536903]


In [19]:
gd.intercept_ - (ss.mean_ / ss.scale_)*gd.coef_ # w_0

array([30774.03773616])

In [20]:
gd.coef_ / ss.scale_ # w_1

array([98.50395317])

In [6]:
w_history = gd._w_history

NameError: name 'gd' is not defined

In [ ]:
## 2020-09-08

from pyvizml import CreateNBAData
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from pyvizml import GradientDescent
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

train = pd.read_csv("https://kaggle-getting-started.s3-ap-northeast-1.amazonaws.com/house-prices/train.csv")
X = train['GrLivArea'].values.reshape(-1, 1)
y = train['SalePrice'].values
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.intercept_) # w_0
print(lr.coef_) # w_1

X

X.max() - X.min() # 5308
X.min() # 334

mms.data_range_ # [5308]
mms.data_min_ # [334]

mms = MinMaxScaler()
X_scaled = mms.fit_transform(X)
X_scaled

(X - X.min()) / (X.max() - X.min())

X_train, X_valid, y_train, y_valid = train_test_split(X_scaled, y, test_size=0.33, random_state=42)
gd = GradientDescent()
gd.fit(X_train, y_train, epochs=100000, learning_rate=0.01)

print(gd.intercept_) # w_0_scaled
print(gd.coef_)      # w_1_scaled

gd.intercept_ - (mms.data_min_ / mms.data_range_) * gd.coef_ # w_0

gd.coef_ / mms.data_range_ # w_1

ss = StandardScaler()
X_scaled = ss.fit_transform(X)
X_scaled

ss.mean_ # 1515.46369863
ss.scale_ # 525.30039356

X.mean()
X.std()

(X - X.mean()) / X.std()

X_train, X_valid, y_train, y_valid = train_test_split(X_scaled, y, test_size=0.33, random_state=42)
gd = GradientDescent()
gd.fit(X_train, y_train, epochs=100000, learning_rate=0.01)

print(gd.intercept_) # w_0_scaled

print(gd.coef_) # w_1_scaled

gd.intercept_ - (ss.mean_ / ss.scale_)*gd.coef_ # w_0

gd.coef_ / ss.scale_ # w_1

w_history = gd._w_history

def plot_contour(X_train, y_train, w_history, w_0_min, w_0_max, w_1_min, w_1_max, w_0_star, w_1_star):
    m = X_train.shape[0]
    X0 = np.ones((m, 1), dtype=float)
    X_train = np.concatenate([X0, X_train], axis=1)
    resolution = 100
    W_0, W_1 = np.meshgrid(np.linspace(w_0_min, w_0_max, resolution), np.linspace(w_1_min, w_1_max, resolution))
    Z = np.zeros((resolution, resolution))
    for i in range(resolution):
        for j in range(resolution):
            w = np.array([W_0[i, j], W_1[i, j]])
            y_hat = np.dot(X_train, w)
            mse = ((y_hat - y_train).T.dot(y_hat - y_train)) / m
            Z[i, j] = mse
    epochs = len(w_history)
    w_0_history = []
    w_1_history = []
    for i in range(epochs):
        w_0_history.append(w_history[i][0])
        w_1_history.append(w_history[i][1])
    fig, ax = plt.subplots()
    CS = ax.contour(W_0, W_1, Z)
    ax.clabel(CS, inline=1, fontsize=10)
    ax.plot(w_0_history, w_1_history, "-", color="blue")
    ax.scatter(w_0_star, w_1_star, marker="*", color="red")
    ax.set_xlabel("$w_0$")
    ax.set_ylabel("$w_1$", rotation=0)
    plt.show()

plot_contour(X_train, y_train, w_history, w_0_min=-100000, w_0_max=360000, w_1_min=-100000, w_1_max=200000, w_0_star=gd.intercept_, w_1_star=gd.coef_[0])

w_history[0]

w_history[99999]

class AdaGrad(GradientDescent):
    def fit(self, X_train, y_train, epochs=10000, learning_rate=0.01, epsilon=1e-06):
        self._X_train = X_train.copy()
        self._y_train = y_train.copy()
        self._m = self._X_train.shape[0]
        if self._fit_intercept:
            X0 = np.ones((self._m, 1), dtype=float)
            self._X_train = np.concatenate([X0, self._X_train], axis=1)
        n = self._X_train.shape[1]
        self._w = np.random.rand(n)
        ssg = np.zeros(n, dtype=float) # 初始化 ssg (n,)
        n_prints = 10
        print_iter = epochs // n_prints
        w_history = dict()
        for i in range(epochs):
            current_w = self._w.copy()
            w_history[i] = current_w
            mse = self.mean_squared_error()
            gradient = self.find_gradient() # (n,)
            ssg += gradient**2 # 更新 ssg
            ada_grad = gradient / (epsilon + ssg**0.5) # adaptive gradient
            if i % print_iter == 0:
                print("epoch: {:6} - loss: {:.6f}".format(i, mse))
            self._w -= learning_rate*ada_grad # 以 adaptive gradient 更新 w
        w_ravel = self._w.copy().ravel()
        self.intercept_ = w_ravel[0]
        self.coef_ = w_ravel[1:]
        self._w_history = w_history

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)
ada_grad = AdaGrad()
ada_grad.fit(X_train, y_train, learning_rate=100, epochs=500000)

ada_grad.intercept_

ada_grad.coef_

w_history = ada_grad._w_history
plot_contour(X_train, y_train, w_history, -5000, 35000, -10, 200, lr.intercept_, lr.coef_[0])

cnd = CreateNBAData(2019)
#player_stats = cnd.create_player_stats_df()
player_stats = pd.read_csv('player_stats.csv')
type(player_stats)

player_stats.shape

y = player_stats['pos'].values
print(type(y))
print(y.dtype)

np.unique(y)

# h(np.array([[5, 10]])) => p_hat => y_hat
p_hat = np.random.random(7).reshape(1, 7)
p_hat

np.unique(y)[np.argmax(p_hat, axis=1)[0]]

pos_dict = {
    0: 'G',
    1: 'F'
}
pos = player_stats['pos'].values
pos_binary = np.array([0 if p[0] == 'G' else 1 for p in pos])

np.unique(pos_binary)

print(pos_binary[:10])
print(pos[:10])

X = player_stats[['apg', 'rpg']].values
print(type(X))
print(X.dtype)

X[:10]

y = pos_binary
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)
h = LogisticRegression(C=1e06) # 預測器的正規化程度
h.fit(X_train, y_train)

h.intercept_

h.coef_

np.argmax(h.predict_proba(X_valid)[:10], axis=1)

h.predict(X_valid)[:10]

X_valid[9, :]

np.median(X_valid[:, 0])

np.median(X_valid[:, 1])

h.predict(X_valid)[:10]

y_valid[:10]

X_valid[6, :]

p_hat = h.predict_proba(X_valid)
y_hat = np.argmax(p_hat, axis=1)
y_pred = [pos_dict[i] for i in y_hat]
print(y_pred)

(y_valid != y_hat).sum()

y_valid.size