In [1]:
from pyvizml import CreateNBAData
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

In [2]:
X0 = np.ones((10, 1))
X1 = np.arange(1, 11).reshape(-1, 1)
print(X0)
print(X1)
w = np.array([5, 6])
print(w)
X_train = np.concatenate([X0, X1], axis=1)
y_train = np.dot(X_train, w)
print(X_train)
print(y_train)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[5 6]
[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]
[11. 17. 23. 29. 35. 41. 47. 53. 59. 65.]


In [3]:
# Create a random set of number.
np.random.seed(42)
w = np.random.rand(2)
w

array([0.37454012, 0.95071431])

In [4]:
y_hat = np.dot(X_train, w)
y_hat

array([1.32525443, 2.27596873, 3.22668304, 4.17739734, 5.12811165,
       6.07882596, 7.02954026, 7.98025457, 8.93096888, 9.88168318])

In [5]:
# Calculate the gap between y_hat and y_train.
m = y_train.size
j = ((y_hat - y_train).T.dot(y_hat - y_train)) / m
j

1259.8713431546198

In [6]:
gradients = (2/m) * np.dot(X_train.T, y_hat - y_train)
gradients

array([ -64.79306239, -439.6750571 ])

In [7]:
learning_rate = 0.001
-learning_rate * gradients

array([0.06479306, 0.43967506])

In [8]:
w -= learning_rate * gradients
# w = w - learning_rate * gradients

In [9]:
w

array([0.43933318, 1.39038936])

In [10]:
y_hat = np.dot(X_train, w)
j = ((y_hat - y_train).T.dot(y_hat - y_train)) / m
j

1070.1192063534622

In [11]:
X0 = np.ones((10, 1))
X1 = np.arange(1, 11).reshape(-1, 1)
print(X0)
print(X1)
w = np.array([5, 6])
print(w)
X_train = np.concatenate([X0, X1], axis=1)
y_train = np.dot(X_train, w)
print(X_train)
print(y_train)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[5 6]
[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]
[11. 17. 23. 29. 35. 41. 47. 53. 59. 65.]


In [12]:
#X_train
#y_train

# Get two random numbers.
w = np.random.random(2)
w

array([0.73199394, 0.59865848])

In [13]:
def calculate_gradients(X_train, y_hat, y_train):
    m = X_train.shape[0]
    X_train_T = np.transpose(X_train) # (n, m)
    error = y_hat - y_train           # (m,)
    gradients = (2/m) * np.dot(X_train_T, error) # (n, m)(m,) = (n,)
    return gradients

In [14]:
#learning_rate
w = np.random.random(2)
learning_rate = 0.001
# learning_rate = 0.01
epochs = 10000
# epochs = 1000
print("original w:{}".format(w))
for _ in range(epochs):
    y_hat = np.dot(X_train, w)
    gradients = calculate_gradients(X_train, y_hat, y_train)
    #j = np.sum(((y_hat - y_train)**2))/y_hat.size => Error.
    w -= learning_rate * gradients
    if _ % 1000 == 0:
        print(w)

original w:[0.15601864 0.15599452]
[0.22999066 0.65926674]
[2.42320807 6.37013181]
[3.30699841 6.24318368]
[3.88766557 6.15977633]
[4.269175   6.10497611]
[4.519834   6.06897131]
[4.68452175 6.04531547]
[4.79272476 6.02977313]
[4.8638162  6.01956152]
[4.91052464 6.01285229]


In [15]:
w

array([4.94118828, 6.00844775])

In [16]:
from pyvizml import GradientDescent

In [17]:
gd = GradientDescent(fit_intercept=False)
gd.fit(X_train, y_train, epochs=1000000)

epoch:      0 - loss: 1318.214422
epoch: 100000 - loss: 0.000000
epoch: 200000 - loss: 0.000000
epoch: 300000 - loss: 0.000000
epoch: 400000 - loss: 0.000000
epoch: 500000 - loss: 0.000000
epoch: 600000 - loss: 0.000000
epoch: 700000 - loss: 0.000000
epoch: 800000 - loss: 0.000000
epoch: 900000 - loss: 0.000000


In [18]:
X_train

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  5.],
       [ 1.,  6.],
       [ 1.,  7.],
       [ 1.,  8.],
       [ 1.,  9.],
       [ 1., 10.]])

In [19]:
y_train

array([11., 17., 23., 29., 35., 41., 47., 53., 59., 65.])

In [20]:
print(gd.coef_)
print(gd.intercept_)

[6.]
4.9999999999988205


In [21]:
gd._w_history[0]

array([0.05808361, 0.86617615])

In [22]:
gd._w_history[1000000-1]

array([5., 6.])