In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pyvizml import CreateNBAData
from tensorflow.keras import datasets

In [2]:
np.random.seed(0)
arr = np.random.randint(1, 100, size=(10,))
print(arr)

[45 48 65 68 68 10 84 22 37 88]


In [3]:
print(arr[[0, 2, -2]]) # fancy indexing
print(arr[[0, 2, -2]]) # fancy indexing

[45 65 37]
[45 65 37]


In [4]:
print(arr % 2)
print(arr % 2 == 1)      # boolean array
print(arr[arr % 2 == 1]) # boolean indexing

[1 0 1 0 0 0 0 0 1 0]
[ True False  True False False False False False  True False]
[45 65 37]


In [5]:
rand_list = list(arr)
print(rand_list)

[45, 48, 65, 68, 68, 10, 84, 22, 37, 88]


In [6]:
list(filter(lambda x : x % 2 == 1, rand_list)) # Apply x % 2 to data of rand_list. 

[45, 65, 37]

In [7]:
is_odd = [True, False, True, False, False, False, False, False, True, False]
print(arr)
print(arr[is_odd])

[45 48 65 68 68 10 84 22 37 88]
[45 65 37]


In [8]:
# Reshape

In [9]:
arr = np.arange(1, 10)
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [10]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# -1 will automatically calculate the rest of number.

In [12]:
arr.reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
cnd = CreateNBAData(2019)
players = cnd.create_players_df()

Creating players df...


In [15]:
players

firstName   lastName temporaryDisplayName personId      teamId jersey  \
0      Jaylen      Adams        Adams, Jaylen  1629121  1610612757     10   
1      Steven      Adams        Adams, Steven   203500  1610612760     12   
2         Bam    Adebayo         Adebayo, Bam  1628389  1610612748     13   
3    LaMarcus   Aldridge   Aldridge, LaMarcus   200746  1610612759     12   
4        Kyle  Alexander      Alexander, Kyle  1629734  1610612748     17   
..        ...        ...                  ...      ...         ...    ...   
505      Trae      Young          Young, Trae  1629027  1610612737     11   
506      Cody     Zeller         Zeller, Cody   203469  1610612766     40   
507     Tyler     Zeller        Zeller, Tyler   203092  1610612759     40   
508      Ante      Zizic          Zizic, Ante  1627790  1610612739     41   
509     Ivica      Zubac         Zubac, Ivica  1627826  1610612746     40   

     isActive  pos heightFeet heightInches heightMeters weightPounds  \
0        True    G          6            0         1.83          225   
1        True    C          6           11         2.11          265   
2        True  C-F          6            9         2.06          255   
3        True  C-F          6           11         2.11          250   
4        True  F-C          6           10         2.08          216   
..        ...  ...        ...          ...          ...          ...   
505      True    G          6            1         1.85          180   
506      True  F-C          7            0         2.13          240   
507      True  F-C          6           11         2.11          250   
508      True    C          6           10         2.08          266   
509      True    C          7            0         2.13          240   

    weightKilograms dateOfBirthUTC nbaDebutYear yearsPro      collegeName  \
0             102.1     1996-05-04         2018        1  St. Bonaventure   
1             120.2     1993-07-20         2013        6       Pittsburgh   
2             115.7     1997-07-18         2017        2         Kentucky   
3             113.4     1985-07-19         2006       13            Texas   
4              98.0     1996-10-21         2019        0        Tennessee   
..              ...            ...          ...      ...              ...   
505            81.6     1998-09-19         2018        1         Oklahoma   
506           108.9     1992-10-05         2013        6          Indiana   
507           113.4     1990-01-17         2012        7   North Carolina   
508           120.7     1997-01-04         2017        2                    
509           108.9     1997-03-18         2016        3                    

                  lastAffiliation      country isallStar  
0             St. Bonaventure/USA          USA       NaN  
1          Pittsburgh/New Zealand  New Zealand       NaN  
2                    Kentucky/USA          USA       NaN  
3                       Texas/USA          USA       NaN  
4                Tennessee/Canada       Canada       NaN  
..                            ...          ...       ...  
505    University of Oklahoma/USA          USA       NaN  
506                   Indiana/USA          USA       NaN  
507            North Carolina/USA          USA       NaN  
508  Darussafaka (Turkey)/Croatia      Croatia       NaN  
509             Mega Leks/Croatia      Croatia       NaN  

[510 rows x 20 columns]

In [16]:
X = players['heightMeters'].values
type(X)

numpy.ndarray

In [17]:
X.shape

(510,)

In [18]:
X.reshape(-1, 1).shape

(510, 1)

In [19]:
# 1D.
# Print first 10 data.
print(X[:10])

['1.83' '2.11' '2.06' '2.11' '2.08' '1.96' '1.93' '2.11' '2.03' '1.96']


In [20]:
# 2D.
# Print first 10 data.
X.reshape(-1, 1)[:10, :]

array([['1.83'],
       ['2.11'],
       ['2.06'],
       ['2.11'],
       ['2.08'],
       ['1.96'],
       ['1.93'],
       ['2.11'],
       ['2.03'],
       ['1.96']], dtype=object)

In [21]:
arr = arr.reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# Return to previous shape.
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# shallow-copy

In [24]:
arr = np.arange(1, 10)
mat = arr.reshape(3, 3) # shallow-copy

In [25]:
print(arr)
print(id(arr))

[1 2 3 4 5 6 7 8 9]
2727589850768


In [26]:
print(mat)
print(id(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2727589847328


In [27]:
mat[1, 1] = 5566
print(mat)

[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]


In [28]:
# Changed arr.
print(arr)

[   1    2    3    4 5566    6    7    8    9]


In [29]:
# Then we should copy first and then reshpae.

In [30]:
arr = np.arange(1, 10)
mat = arr.copy()
mat = mat.reshape(3, -1)
mat[1, 1] = 5566
print(mat)
print(arr)

[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]
[1 2 3 4 5 6 7 8 9]


In [31]:
# Combine and concatenate.

In [32]:
arr_a = np.arange(1, 5).reshape(2, 2)
arr_b = np.arange(5, 9).reshape(2, 2)
print(np.concatenate([arr_a, arr_b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
print(np.concatenate([arr_a, arr_b], axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
# Universal function.

In [35]:
long_arr = np.random.randint(1, 101, size=1000000)
%timeit [1/i for i in long_arr]

466 ms ± 25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
long_arr = np.random.randint(1, 101, size=1000000)
%timeit np.divide(1, long_arr)

4.9 ms ± 550 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
def is_prime(x):
    div_cnt = 0
    for i in range(1, x+1):
        if x % i == 0:
            div_cnt += 1
        if div_cnt > 2:
            break
    return div_cnt == 2

In [38]:
is_prime(2)

True

In [39]:
# Vectorize.

In [40]:
arr = np.random.randint(1, 100, 100)
arr

array([98, 34, 59, 68, 21, 76, 77, 88,  1, 32,  7, 98, 34, 48,  3, 28, 93,
       94, 27, 22, 57, 54, 69, 24, 94, 20, 39, 44, 51, 36, 80, 45, 52, 37,
       84, 79, 66, 31, 77,  3, 59, 90, 58,  2,  8, 38, 78, 63, 85, 54, 86,
       66, 63, 26, 81, 79, 15, 36, 13, 62, 64, 93,  2, 50, 95, 31, 36, 99,
       73,  7,  1, 65,  3, 49, 56, 70, 56, 42, 74, 62, 75, 58, 34, 84, 15,
       41, 60, 40, 27, 42, 38,  1, 59, 56, 17, 49, 77, 36, 95, 62])

In [41]:
[is_prime(i) for i in arr]

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False]

In [42]:
prime_list = [is_prime(i) for i in arr]
print(prime_list)

[False, False, True, False, False, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, False, True, False, True, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, True, False, False, True, False, False, False, True, False, False, True, False, False, True, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, True, False, False, False, False, False]


In [43]:
print(prime_list)

[False, False, True, False, False, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, False, True, False, True, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, True, False, False, True, False, False, False, True, False, False, True, False, False, True, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, True, False, False, False, False, False]


In [44]:
type(is_prime)

function

In [45]:
is_prime_ufunc = np.vectorize(is_prime)
type(is_prime_ufunc)

numpy.vectorize

In [46]:
is_prime_ufunc(arr)

array([False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False,  True,
       False, False,  True, False, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False])

In [47]:
# .replace
# .str.replace

In [48]:
# replace apply to only one object.
"Luke Skywalker".replace("Luke", "Anakin")

'Anakin Skywalker'

In [49]:
# str.replace apply to multiple objects.
ser = pd.Series(["Luke Skywalker", "Anakin Skywalker"])
ser.str.replace(" Skywalker", "") # Replace "Skywalker" with "".

0      Luke
1    Anakin
dtype: object