In [1]:
from pyvizml import CreateNBAData
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures

In [2]:
# Initiation.
cnb = CreateNBAData(2019)
players = cnb.create_players_df()

Creating players df...


In [3]:
players

firstName   lastName temporaryDisplayName personId      teamId jersey  \
0      Jaylen      Adams        Adams, Jaylen  1629121  1610612757     10   
1      Steven      Adams        Adams, Steven   203500  1610612760     12   
2         Bam    Adebayo         Adebayo, Bam  1628389  1610612748     13   
3    LaMarcus   Aldridge   Aldridge, LaMarcus   200746  1610612759     12   
4        Kyle  Alexander      Alexander, Kyle  1629734  1610612748     17   
..        ...        ...                  ...      ...         ...    ...   
505      Trae      Young          Young, Trae  1629027  1610612737     11   
506      Cody     Zeller         Zeller, Cody   203469  1610612766     40   
507     Tyler     Zeller        Zeller, Tyler   203092  1610612759     40   
508      Ante      Zizic          Zizic, Ante  1627790  1610612739     41   
509     Ivica      Zubac         Zubac, Ivica  1627826  1610612746     40   

     isActive  pos heightFeet heightInches heightMeters weightPounds  \
0        True    G          6            0         1.83          225   
1        True    C          6           11         2.11          265   
2        True  C-F          6            9         2.06          255   
3        True  C-F          6           11         2.11          250   
4        True  F-C          6           10         2.08          216   
..        ...  ...        ...          ...          ...          ...   
505      True    G          6            1         1.85          180   
506      True  F-C          7            0         2.13          240   
507      True  F-C          6           11         2.11          250   
508      True    C          6           10         2.08          266   
509      True    C          7            0         2.13          240   

    weightKilograms dateOfBirthUTC nbaDebutYear yearsPro      collegeName  \
0             102.1     1996-05-04         2018        1  St. Bonaventure   
1             120.2     1993-07-20         2013        6       Pittsburgh   
2             115.7     1997-07-18         2017        2         Kentucky   
3             113.4     1985-07-19         2006       13            Texas   
4              98.0     1996-10-21         2019        0        Tennessee   
..              ...            ...          ...      ...              ...   
505            81.6     1998-09-19         2018        1         Oklahoma   
506           108.9     1992-10-05         2013        6          Indiana   
507           113.4     1990-01-17         2012        7   North Carolina   
508           120.7     1997-01-04         2017        2                    
509           108.9     1997-03-18         2016        3                    

                  lastAffiliation      country isallStar  
0             St. Bonaventure/USA          USA       NaN  
1          Pittsburgh/New Zealand  New Zealand       NaN  
2                    Kentucky/USA          USA       NaN  
3                       Texas/USA          USA       NaN  
4                Tennessee/Canada       Canada       NaN  
..                            ...          ...       ...  
505    University of Oklahoma/USA          USA       NaN  
506                   Indiana/USA          USA       NaN  
507            North Carolina/USA          USA       NaN  
508  Darussafaka (Turkey)/Croatia      Croatia       NaN  
509             Mega Leks/Croatia      Croatia       NaN  

[510 rows x 20 columns]

In [4]:
X = players['heightMeters'].values

In [5]:
X

array(['1.83', '2.11', '2.06', '2.11', '2.08', '1.96', '1.93', '2.11',
       '2.03', '1.96', '2.06', '2.11', '2.08', '1.98', '2.03', '2.01',
       '1.9', '2.03', '1.8', '2.11', '1.98', '2.11', '1.98', '2.13',
       '1.78', '2.03', '1.98', '1.96', '2.03', '2.06', '2.08', '1.93',
       '2.03', '1.9', '1.93', '1.96', '2.03', '1.96', '2.08', '1.85',
       '2.06', '2.11', '2.03', '2.08', '1.85', '1.98', '2.03', '2.18',
       '1.9', '2.03', '1.96', '2.06', '1.98', '1.85', '1.9', '2.08',
       '1.96', '1.98', '2.06', '1.98', '1.98', '2.01', '1.98', '1.96',
       '2.01', '1.93', '1.98', '2.18', '1.96', '1.98', '1.98', '1.85',
       '2.08', '1.98', '1.83', '1.98', '1.93', '2.01', '2.06', '2.03',
       '1.96', '2.03', '2.08', '1.98', '1.85', '1.98', '2.06', '1.96',
       '1.96', '2.13', '2.13', '2.03', '1.96', '1.8', '2.06', '1.98',
       '2.03', '1.93', '2.11', '1.75', '1.96', '2.01', '2.06', '2.11',
       '1.85', '1.96', '1.85', '2.03', '2.01', '2.01', '1.96', '1.98',
       '1.98

In [6]:
X = players['heightMeters'].values.astype(float)

In [7]:
X

array([1.83, 2.11, 2.06, 2.11, 2.08, 1.96, 1.93, 2.11, 2.03, 1.96, 2.06,
       2.11, 2.08, 1.98, 2.03, 2.01, 1.9 , 2.03, 1.8 , 2.11, 1.98, 2.11,
       1.98, 2.13, 1.78, 2.03, 1.98, 1.96, 2.03, 2.06, 2.08, 1.93, 2.03,
       1.9 , 1.93, 1.96, 2.03, 1.96, 2.08, 1.85, 2.06, 2.11, 2.03, 2.08,
       1.85, 1.98, 2.03, 2.18, 1.9 , 2.03, 1.96, 2.06, 1.98, 1.85, 1.9 ,
       2.08, 1.96, 1.98, 2.06, 1.98, 1.98, 2.01, 1.98, 1.96, 2.01, 1.93,
       1.98, 2.18, 1.96, 1.98, 1.98, 1.85, 2.08, 1.98, 1.83, 1.98, 1.93,
       2.01, 2.06, 2.03, 1.96, 2.03, 2.08, 1.98, 1.85, 1.98, 2.06, 1.96,
       1.96, 2.13, 2.13, 2.03, 1.96, 1.8 , 2.06, 1.98, 2.03, 1.93, 2.11,
       1.75, 1.96, 2.01, 2.06, 2.11, 1.85, 1.96, 1.85, 2.03, 2.01, 2.01,
       1.96, 1.98, 1.98, 1.88, 1.9 , 1.93, 2.08, 2.06, 1.93, 2.13, 1.9 ,
       1.98, 2.03, 1.96, 2.08, 1.96, 1.93, 2.01, 1.9 , 1.96, 2.03, 1.98,
       1.9 , 2.08, 1.98, 1.9 , 2.08, 1.8 , 1.93, 2.13, 1.98, 2.06, 1.93,
       1.96, 2.26, 2.06, 2.08, 1.98, 2.06, 1.83, 2.

In [8]:
X = players['heightMeters'].values.astype(float).reshape(-1, 1)

In [9]:
X

array([[1.83],
       [2.11],
       [2.06],
       [2.11],
       [2.08],
       [1.96],
       [1.93],
       [2.11],
       [2.03],
       [1.96],
       [2.06],
       [2.11],
       [2.08],
       [1.98],
       [2.03],
       [2.01],
       [1.9 ],
       [2.03],
       [1.8 ],
       [2.11],
       [1.98],
       [2.11],
       [1.98],
       [2.13],
       [1.78],
       [2.03],
       [1.98],
       [1.96],
       [2.03],
       [2.06],
       [2.08],
       [1.93],
       [2.03],
       [1.9 ],
       [1.93],
       [1.96],
       [2.03],
       [1.96],
       [2.08],
       [1.85],
       [2.06],
       [2.11],
       [2.03],
       [2.08],
       [1.85],
       [1.98],
       [2.03],
       [2.18],
       [1.9 ],
       [2.03],
       [1.96],
       [2.06],
       [1.98],
       [1.85],
       [1.9 ],
       [2.08],
       [1.96],
       [1.98],
       [2.06],
       [1.98],
       [1.98],
       [2.01],
       [1.98],
       [1.96],
       [2.01],
       [1.93],
       [1.

In [10]:
X = players['heightMeters'].values.astype(float).reshape(-1, 1)
y = players['weightKilograms'].values.astype(float)
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42) # random_state => shuffle
h = LinearRegression()
# h = LinearRegression(fir_intercept=False)
h.fit(X_train, y_train)
print(h.coef_)
print(h.intercept_)
h.predict(X_valid)[:10]

[96.22270241]
-93.22909204641577


array([102.10299386, 102.10299386,  95.36740469,  82.85845337,
       100.17853981, 106.91412898,  97.29185874,  92.48072361,
       102.10299386, 100.17853981])

In [11]:
# Wrtie a class to simulate LinearRegression() function.

In [12]:
class NormalEquation:
    def __init__(self, fit_intercept=True):
        self._fit_intercept = fit_intercept
    def fit(self, X_train, y_train):
        self._X_train = X_train.copy() # Not affect original data.
        self._y_train = y_train.copy() # Not affect original data.
        m = self._X_train.shape[0]
        
        # Determine add intercept or not.
        if self._fit_intercept:
            X0 = np.ones(m).reshape(-1, 1)
            self._X_train = np.concatenate([X0, self._X_train], axis=1) # axis=1 => row
        X_train_T = np.transpose(self._X_train)
        left_matrix = np.dot(X_train_T, self._X_train)  # (2, m)(m, 2) = (2, 2)
        right_matrix = np.dot(X_train_T, self._y_train) # (2, m)(m,) = (2,)
        left_matrix_inv = np.linalg.inv(left_matrix)    
        w = np.dot(left_matrix_inv, right_matrix)       # (2, 2)(2,) = (2,)
        self._w = w
        self.intercept_ = w[0]
        self.coef_ = w[1:]
    def predict(self, X):
        m = X.shape[0]
        if self._fit_intercept:
            X0 = np.ones(m).reshape(-1, 1)
            X = np.concatenate([X0, X], axis=1)
        y_pred = np.dot(X, self._w) # (m, 2)(2, ) = (m,)
        return y_pred

In [13]:
h = NormalEquation()
h.fit(X_train, y_train)

In [14]:
h._X_train.shape

(341, 2)

In [15]:
h._X_train[:5]

array([[1.  , 1.85],
       [1.  , 2.24],
       [1.  , 2.06],
       [1.  , 2.01],
       [1.  , 2.11]])

In [16]:
print(h.intercept_)
print(h.coef_)

-93.22909204637108
[96.22270241]


In [17]:
h.predict(X_valid)[:10]

array([102.10299386, 102.10299386,  95.36740469,  82.85845337,
       100.17853981, 106.91412898,  97.29185874,  92.48072361,
       102.10299386, 100.17853981])

\begin{equation}
w^* = (X^TX)^{-1}X^Ty
\end{equation}