In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
from tensorflow.keras import datasets
from pyvizml import CreateNBAData
import requests
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_boston
from sklearn.datasets import fetch_california_housing
from sklearn.datasets import make_classification
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
cnb = CreateNBAData(2019)
players = cnb.create_players_df()
X = players['heightMeters'].values.reshape(-1, 1)
y = players['weightKilograms'].values

Creating players df...


In [3]:
cnb

In [4]:
players

firstName   lastName temporaryDisplayName personId      teamId jersey  \
0      Jaylen      Adams        Adams, Jaylen  1629121  1610612757     10   
1      Steven      Adams        Adams, Steven   203500  1610612760     12   
2         Bam    Adebayo         Adebayo, Bam  1628389  1610612748     13   
3    LaMarcus   Aldridge   Aldridge, LaMarcus   200746  1610612759     12   
4        Kyle  Alexander      Alexander, Kyle  1629734  1610612748     17   
..        ...        ...                  ...      ...         ...    ...   
505      Trae      Young          Young, Trae  1629027  1610612737     11   
506      Cody     Zeller         Zeller, Cody   203469  1610612766     40   
507     Tyler     Zeller        Zeller, Tyler   203092  1610612759     40   
508      Ante      Zizic          Zizic, Ante  1627790  1610612739     41   
509     Ivica      Zubac         Zubac, Ivica  1627826  1610612746     40   

     isActive  pos heightFeet heightInches heightMeters weightPounds  \
0        True    G          6            0         1.83          225   
1        True    C          6           11         2.11          265   
2        True  C-F          6            9         2.06          255   
3        True  C-F          6           11         2.11          250   
4        True  F-C          6           10         2.08          216   
..        ...  ...        ...          ...          ...          ...   
505      True    G          6            1         1.85          180   
506      True  F-C          7            0         2.13          240   
507      True  F-C          6           11         2.11          250   
508      True    C          6           10         2.08          266   
509      True    C          7            0         2.13          240   

    weightKilograms dateOfBirthUTC nbaDebutYear yearsPro      collegeName  \
0             102.1     1996-05-04         2018        1  St. Bonaventure   
1             120.2     1993-07-20         2013        6       Pittsburgh   
2             115.7     1997-07-18         2017        2         Kentucky   
3             113.4     1985-07-19         2006       13            Texas   
4              98.0     1996-10-21         2019        0        Tennessee   
..              ...            ...          ...      ...              ...   
505            81.6     1998-09-19         2018        1         Oklahoma   
506           108.9     1992-10-05         2013        6          Indiana   
507           113.4     1990-01-17         2012        7   North Carolina   
508           120.7     1997-01-04         2017        2                    
509           108.9     1997-03-18         2016        3                    

                  lastAffiliation      country isallStar  
0             St. Bonaventure/USA          USA       NaN  
1          Pittsburgh/New Zealand  New Zealand       NaN  
2                    Kentucky/USA          USA       NaN  
3                       Texas/USA          USA       NaN  
4                Tennessee/Canada       Canada       NaN  
..                            ...          ...       ...  
505    University of Oklahoma/USA          USA       NaN  
506                   Indiana/USA          USA       NaN  
507            North Carolina/USA          USA       NaN  
508  Darussafaka (Turkey)/Croatia      Croatia       NaN  
509             Mega Leks/Croatia      Croatia       NaN  

[510 rows x 20 columns]

In [5]:
X

array([['1.83'],
       ['2.11'],
       ['2.06'],
       ['2.11'],
       ['2.08'],
       ['1.96'],
       ['1.93'],
       ['2.11'],
       ['2.03'],
       ['1.96'],
       ['2.06'],
       ['2.11'],
       ['2.08'],
       ['1.98'],
       ['2.03'],
       ['2.01'],
       ['1.9'],
       ['2.03'],
       ['1.8'],
       ['2.11'],
       ['1.98'],
       ['2.11'],
       ['1.98'],
       ['2.13'],
       ['1.78'],
       ['2.03'],
       ['1.98'],
       ['1.96'],
       ['2.03'],
       ['2.06'],
       ['2.08'],
       ['1.93'],
       ['2.03'],
       ['1.9'],
       ['1.93'],
       ['1.96'],
       ['2.03'],
       ['1.96'],
       ['2.08'],
       ['1.85'],
       ['2.06'],
       ['2.11'],
       ['2.03'],
       ['2.08'],
       ['1.85'],
       ['1.98'],
       ['2.03'],
       ['2.18'],
       ['1.9'],
       ['2.03'],
       ['1.96'],
       ['2.06'],
       ['1.98'],
       ['1.85'],
       ['1.9'],
       ['2.08'],
       ['1.96'],
       ['1.98'],
       ['2.06'],
  

In [6]:
y

array(['102.1', '120.2', '115.7', '113.4', '98.0', '93.0', '89.8',
       '110.2', '99.8', '104.8', '104.3', '109.8', '90.7', '99.3',
       '108.0', '105.2', '88.5', '97.5', '83.0', '113.4', '100.2',
       '106.6', '86.2', '104.8', '81.6', '102.1', '97.1', '82.1', '103.9',
       '104.3', '117.9', '88.5', '94.3', '93.9', '84.8', '99.8', '98.0',
       '95.3', '102.1', '81.6', '105.7', '113.4', '115.7', '106.1',
       '97.1', '99.8', '102.5', '99.8', '81.6', '81.6', '93.4', '90.7',
       '86.2', '84.8', '81.6', '112.5', '113.4', '100.2', '85.3', '94.8',
       '102.1', '95.3', '97.5', '103.9', '102.1', '91.6', '101.2',
       '111.1', '99.3', '90.3', '97.5', '86.2', '112.5', '93.0', '83.9',
       '97.1', '108.9', '104.3', '98.9', '108.9', '92.5', '107.0',
       '108.9', '97.5', '90.7', '99.8', '122.5', '86.2', '84.4', '108.9',
       '106.6', '106.6', '99.8', '79.4', '108.9', '102.1', '97.5', '88.0',
       '97.5', '81.6', '88.5', '95.3', '106.6', '113.4', '79.4', '94.8',
       '

In [7]:
X.shape
y.shape
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(341, 1)
(169, 1)
(341,)
(169,)


In [9]:
ss = StandardScaler()
lr = LinearRegression()

In [10]:
type(ss) # transformer
type(lr) # predictor

sklearn.linear_model._base.LinearRegression

In [11]:
pipeline = Pipeline([('scaler', ss), ('lr', lr)])
type(pipeline)

sklearn.pipeline.Pipeline

In [12]:
pipeline.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('lr',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [13]:
pipeline.predict(X_valid)

array([102.10299386, 102.10299386,  95.36740469,  82.85845337,
       100.17853981, 106.91412898,  97.29185874,  92.48072361,
       102.10299386, 100.17853981, 109.80081005,  97.29185874,
       104.98967493,  89.59404254,  95.36740469,  79.9717723 ,
       100.17853981, 100.17853981,  92.48072361,  97.29185874,
        84.78290742,  95.36740469, 111.7252641 , 102.10299386,
        97.29185874,  97.29185874,  84.78290742, 106.91412898,
        89.59404254, 111.7252641 ,  95.36740469,  97.29185874,
       102.10299386,  97.29185874,  97.29185874,  95.36740469,
       100.17853981, 100.17853981, 104.98967493,  89.59404254,
       100.17853981, 104.98967493,  95.36740469, 104.98967493,
        95.36740469,  89.59404254, 106.91412898,  97.29185874,
        89.59404254, 104.98967493, 102.10299386, 100.17853981,
        95.36740469, 104.98967493, 102.10299386,  92.48072361,
        89.59404254, 102.10299386, 100.17853981,  95.36740469,
        95.36740469,  82.85845337,  84.78290742, 109.80

In [14]:
lr.coef_

array([8.53366403])

In [15]:
lr.intercept_

98.95953079178885

In [16]:
X_valid[0, :]

array(['2.03'], dtype=object)

In [17]:
ss.transform(np.array([2.03]).reshape(-1, 1)) * 8.53366403 + lr.intercept_

array([[102.10299386]])

In [18]:
X = players[['heightFeet', 'heightInches']].values.astype(float)
X.shape

(510, 2)

In [19]:
X

array([[ 6.,  0.],
       [ 6., 11.],
       [ 6.,  9.],
       ...,
       [ 6., 11.],
       [ 6., 10.],
       [ 7.,  0.]])

In [20]:
print(X.ndim)
print(X.shape)

2
(510, 2)


In [21]:
y

array(['102.1', '120.2', '115.7', '113.4', '98.0', '93.0', '89.8',
       '110.2', '99.8', '104.8', '104.3', '109.8', '90.7', '99.3',
       '108.0', '105.2', '88.5', '97.5', '83.0', '113.4', '100.2',
       '106.6', '86.2', '104.8', '81.6', '102.1', '97.1', '82.1', '103.9',
       '104.3', '117.9', '88.5', '94.3', '93.9', '84.8', '99.8', '98.0',
       '95.3', '102.1', '81.6', '105.7', '113.4', '115.7', '106.1',
       '97.1', '99.8', '102.5', '99.8', '81.6', '81.6', '93.4', '90.7',
       '86.2', '84.8', '81.6', '112.5', '113.4', '100.2', '85.3', '94.8',
       '102.1', '95.3', '97.5', '103.9', '102.1', '91.6', '101.2',
       '111.1', '99.3', '90.3', '97.5', '86.2', '112.5', '93.0', '83.9',
       '97.1', '108.9', '104.3', '98.9', '108.9', '92.5', '107.0',
       '108.9', '97.5', '90.7', '99.8', '122.5', '86.2', '84.4', '108.9',
       '106.6', '106.6', '99.8', '79.4', '108.9', '102.1', '97.5', '88.0',
       '97.5', '81.6', '88.5', '95.3', '106.6', '113.4', '79.4', '94.8',
       '

In [22]:
print(y.ndim)
print(y.shape)

1
(510,)


In [23]:
poly = PolynomialFeatures()
type(poly)

sklearn.preprocessing._data.PolynomialFeatures

In [24]:
X_before_poly = X.copy()
X_before_poly.shape

(510, 2)

In [25]:
X_after_poly = poly.fit_transform(X)
X_after_poly.shape

(510, 6)

In [26]:
X_before_poly[:10, :]

array([[ 6.,  0.],
       [ 6., 11.],
       [ 6.,  9.],
       [ 6., 11.],
       [ 6., 10.],
       [ 6.,  5.],
       [ 6.,  4.],
       [ 6., 11.],
       [ 6.,  8.],
       [ 6.,  5.]])

In [27]:
X_after_poly[:10, :]

array([[  1.,   6.,   0.,  36.,   0.,   0.],
       [  1.,   6.,  11.,  36.,  66., 121.],
       [  1.,   6.,   9.,  36.,  54.,  81.],
       [  1.,   6.,  11.,  36.,  66., 121.],
       [  1.,   6.,  10.,  36.,  60., 100.],
       [  1.,   6.,   5.,  36.,  30.,  25.],
       [  1.,   6.,   4.,  36.,  24.,  16.],
       [  1.,   6.,  11.,  36.,  66., 121.],
       [  1.,   6.,   8.,  36.,  48.,  64.],
       [  1.,   6.,   5.,  36.,  30.,  25.]])

In [28]:
poly = PolynomialFeatures(degree=1)
X_after_poly = poly.fit_transform(X)
X_after_poly.shape

(510, 3)

In [29]:
X_after_poly

array([[ 1.,  6.,  0.],
       [ 1.,  6., 11.],
       [ 1.,  6.,  9.],
       ...,
       [ 1.,  6., 11.],
       [ 1.,  6., 10.],
       [ 1.,  7.,  0.]])

In [30]:
poly = PolynomialFeatures(degree=3)
X_after_poly = poly.fit_transform(X)
X_after_poly.shape

(510, 10)

In [31]:
X_after_poly

array([[1.000e+00, 6.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 6.000e+00, 1.100e+01, ..., 3.960e+02, 7.260e+02,
        1.331e+03],
       [1.000e+00, 6.000e+00, 9.000e+00, ..., 3.240e+02, 4.860e+02,
        7.290e+02],
       ...,
       [1.000e+00, 6.000e+00, 1.100e+01, ..., 3.960e+02, 7.260e+02,
        1.331e+03],
       [1.000e+00, 6.000e+00, 1.000e+01, ..., 3.600e+02, 6.000e+02,
        1.000e+03],
       [1.000e+00, 7.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [32]:
X_before_scaled = X.copy()
ms = MinMaxScaler()
ss = StandardScaler()

In [33]:
X_before_poly[:10, :]

array([[ 6.,  0.],
       [ 6., 11.],
       [ 6.,  9.],
       [ 6., 11.],
       [ 6., 10.],
       [ 6.,  5.],
       [ 6.,  4.],
       [ 6., 11.],
       [ 6.,  8.],
       [ 6.,  5.]])

In [34]:
max_val = X[:, 0].max() # 7
min_val = X[:, 0].min() # 5
(7-6)/(7-5)

0.5

In [35]:
X_after_ms = ms.fit_transform(X_before_scaled)
print(X_after_ms[:10])

[[0.5        0.        ]
 [0.5        1.        ]
 [0.5        0.81818182]
 [0.5        1.        ]
 [0.5        0.90909091]
 [0.5        0.45454545]
 [0.5        0.36363636]
 [0.5        1.        ]
 [0.5        0.72727273]
 [0.5        0.45454545]]


In [36]:
mean_val = X[:, 0].max() # 7
std_val = X[:, 0].min() # 5
(7 - 6) / (7-5)

0.5

In [37]:
X_after_ss = ss.fit_transform(X_before_scaled)
print(X_after_ss[:10])

[[-0.15058117 -1.89979194]
 [-0.15058117  1.62929176]
 [-0.15058117  0.98764018]
 [-0.15058117  1.62929176]
 [-0.15058117  1.30846597]
 [-0.15058117 -0.29566298]
 [-0.15058117 -0.61648877]
 [-0.15058117  1.62929176]
 [-0.15058117  0.66681439]
 [-0.15058117 -0.29566298]]


In [38]:
train = pd.read_csv("https://kaggle-getting-started.s3-ap-northeast-1.amazonaws.com/titanic/train.csv")
test = pd.read_csv("https://kaggle-getting-started.s3-ap-northeast-1.amazonaws.com/titanic/test.csv")
print(train.shape)
print(test.shape)

(891, 12)
(418, 11)


In [39]:
train.columns.difference(test.columns)

Index(['Survived'], dtype='object')

In [40]:
players.iloc[:5, :4]

firstName   lastName temporaryDisplayName personId
0    Jaylen      Adams        Adams, Jaylen  1629121
1    Steven      Adams        Adams, Steven   203500
2       Bam    Adebayo         Adebayo, Bam  1628389
3  LaMarcus   Aldridge   Aldridge, LaMarcus   200746
4      Kyle  Alexander      Alexander, Kyle  1629734

In [41]:
players_train, players_valid = train_test_split(players, test_size=0.3, random_state=42)

In [42]:
print(players_train.shape)
print(players_valid.shape)
153 / (153+357)

(357, 20)
(153, 20)


0.3

In [43]:
players_train.iloc[:5, :4]

firstName          lastName       temporaryDisplayName personId
23         Mo             Bamba                  Bamba, Mo  1628964
231     Kyrie            Irving              Irving, Kyrie   202681
265      John           Konchar              Konchar, John  1629723
208     Buddy             Hield               Hield, Buddy  1627741
5     Nickeil  Alexander-Walker  Alexander-Walker, Nickeil  1629638

In [44]:
players_valid.iloc[:5, :4]

firstName   lastName temporaryDisplayName personId
480      Yuta   Watanabe       Watanabe, Yuta  1629139
449     Lance     Thomas        Thomas, Lance   202498
475    Lonnie  Walker IV    Walker IV, Lonnie  1629022
434       Ish      Smith           Smith, Ish   202397
368      Cedi      Osman          Osman, Cedi  1626224

In [45]:
def trainTestSplit(df, test_size, random_state):
    df_index = df.index.values.copy()
    m = df_index.size
    np.random.seed(random_state)
    np.random.shuffle(df_index)
    test_index = int(np.ceil(m * test_size))
    test_indices = df_index[:test_index]
    train_indices = df_index[test_index:]
    df_valid = df.loc[test_indices, :]
    df_train = df.loc[train_indices, :]
    return df_train, df_valid

In [46]:
players_train, players_valid = trainTestSplit(players, test_size=0.3, random_state=42)

In [47]:
players_train.iloc[:5, :4]

firstName          lastName       temporaryDisplayName personId
23         Mo             Bamba                  Bamba, Mo  1628964
231     Kyrie            Irving              Irving, Kyrie   202681
265      John           Konchar              Konchar, John  1629723
208     Buddy             Hield               Hield, Buddy  1627741
5     Nickeil  Alexander-Walker  Alexander-Walker, Nickeil  1629638

In [48]:
players_valid.iloc[:5, :4]

firstName   lastName temporaryDisplayName personId
480      Yuta   Watanabe       Watanabe, Yuta  1629139
449     Lance     Thomas        Thomas, Lance   202498
475    Lonnie  Walker IV    Walker IV, Lonnie  1629022
434       Ish      Smith           Smith, Ish   202397
368      Cedi      Osman          Osman, Cedi  1626224